config_version = 6

[fastly]
account_endpoint = "https://accounts.fastly.com"
api_endpoint = "https://api.fastly.com"

[wasm-metadata]
build_info = "enable"
machine_info = "disable"
package_info = "enable"
script_info = "enable"

[language.go]
tinygo_constraint = ">= 0.28.1-0"
tinygo_constraint_fallback = ">= 0.26.0-0"
toolchain_constraint = ">= 1.21"
toolchain_constraint_tinygo = ">= 1.18"

[language.rust]
toolchain_constraint = ">= 1.56.1"
wasm_wasi_target = "wasm32-wasi"

[wasm-tools]
ttl = "24h"

[viceroy]
ttl = "24h"

[[starter-kits.javascript]]
name = "OAuth 2.0 implementation for JavaScript"
description = "Connect to an identity provider such as Google using OAuth 2.0 and validate authentication status at the Edge, to authorize access to your edge or origin hosted applications."
path = "https://github.com/fastly/compute-js-auth"

[[starter-kits.javascript]]
name = "Default starter for JavaScript"
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
path = "https://github.com/fastly/compute-starter-kit-javascript-default"

[[starter-kits.javascript]]
name = "Empty starter for JavaScript"
description = "An empty application template for the Fastly Compute environment which returns a 200 OK response."
path = "https://github.com/fastly/compute-starter-kit-javascript-empty"

[[starter-kits.javascript]]
name = "Default starter kit for expressly"
description = "A basic expressly starter kit that demonstrates simple GET, POST, and middleware functionality."
path = "https://github.com/fastly/compute-starter-kit-javascript-expressly"

[[starter-kits.javascript]]
name = "OpenAPI Validation (JS)"
description = "Application template for validating requests against an OpenAPI document."
path = "https://github.com/fastly/compute-starter-kit-javascript-openapi-validation"

[[starter-kits.javascript]]
name = "Fanout forwarding starter kit for JavaScript"
description = "Enables Fanout on a service, forwarding to a backend."
path = "https://github.com/fastly/compute-starter-kit-javascript-fanout-forward"

[[starter-kits.javascript]]
name = "Queuing / Waiting room (JS)"
description = "Park your users in a virtual queue to reduce the demand on your origins during peak times."
path = "https://github.com/fastly/compute-starter-kit-javascript-queue"

[[starter-kits.javascript]]
name = "Default starter for TypeScript"
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
path = "https://github.com/fastly/compute-starter-kit-typescript"

[[starter-kits.javascript]]
name = "kv-store-typescript-starter-kit"
description = "A TypeScript starter kit that uses Fastly's KV Store."
path = "https://github.com/fastly/compute-starter-kit-typescript-kv-store"

[[starter-kits.rust]]
name = "Auth at edge with OAuth 2.0"
description = "Connect to an identity provider such as Google using OAuth 2.0 and validate authentication status at the Edge, to authorize access to your edge or origin hosted applications."
path = "https://github.com/fastly/compute-rust-auth"

[[starter-kits.rust]]
name = "Beacon termination"
description = "Capture beacon data from the browser, divert beacon request payloads to a log endpoint, and avoid putting load on your own infrastructure."
path = "https://github.com/fastly/compute-starter-kit-rust-beacon-termination"

[[starter-kits.rust]]
name = "Connect to Google Bigquery for Rust"
description = "Fastly Compute starter kit for Google Bigquery Connector."
path = "https://github.com/fastly/compute-starter-kit-rust-connect-google-bigquery"

[[starter-kits.rust]]
name = "Default starter for Rust"
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
path = "https://github.com/fastly/compute-starter-kit-rust-default"

[[starter-kits.rust]]
name = "Empty starter for Rust"
description = "An empty starter kit project template."
path = "https://github.com/fastly/compute-starter-kit-rust-empty"

[[starter-kits.rust]]
name = "Push messaging using Fanout"
description = "Implements Fanout handlers for WebSockets, SSE, etc."
path = "https://github.com/fastly/compute-starter-kit-rust-fanout"

[[starter-kits.rust]]
name = "Fanout forwarding"
description = "Enables Fanout on a service, forwarding to a backend."
path = "https://github.com/fastly/compute-starter-kit-rust-fanout-forward"

[[starter-kits.rust]]
name = "kv-store-rust-starter-kit"
description = "A Rust starter kit that uses Fastly's KV Store."
path = "https://github.com/fastly/compute-starter-kit-rust-kv-store"

[[starter-kits.rust]]
name = "Static content"
description = "Apply performance, security and usability upgrades to static bucket services such as Google Cloud Storage or AWS S3."
path = "https://github.com/fastly/compute-starter-kit-rust-static-content"

[[starter-kits.rust]]
name = "WebSockets passthrough"
description = "Implements WebSocket passthrough."
path = "https://github.com/fastly/compute-starter-kit-rust-websockets"

[[starter-kits.go]]
name = "Default starter for Go"
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
path = "https://github.com/fastly/compute-starter-kit-go-default"

[[starter-kits.go]]
name = "kv-store-go-starter-kit"
description = "A Go starter kit that uses Fastly's KV Store."
path = "https://github.com/fastly/compute-starter-kit-go-kv-store"
