[env]
CARGO_BIN = '@cargoBin@'
CARGO_ALL_FEATURES = '0'
CARGO_FEATURES = ''
CARGO_WORKSPACE = '0'
CARGO_TARGET = ''
CARGO_PROFILE = ''
CARGO_BENCH_BACKEND = 'bench'

CARGO_WORKSPACE_PREFIX = ''

CARGO_PROFILE_RELEASE_DEBUG = 'true'
